/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.users;

import java.awt.Color;

/**
 *
 * @author baotri1998
 */
public class Quanlyusers extends javax.swing.JPanel {

    /**
     * Creates new form Quanlyusers
     */
    public Quanlyusers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSSanPham = new javax.swing.JScrollPane();
        jpnDSsanpham = new javax.swing.JPanel();

        jSSanPham.setBackground(Color.decode("#e6e6e6"));
        jSSanPham.setBorder(null);
        jSSanPham.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpnDSsanpham.setBackground(new java.awt.Color(255, 255, 255));
        jpnDSsanpham.setAutoscrolls(true);
        jpnDSsanpham.setMaximumSize(new java.awt.Dimension(32767, 400));

        javax.swing.GroupLayout jpnDSsanphamLayout = new javax.swing.GroupLayout(jpnDSsanpham);
        jpnDSsanpham.setLayout(jpnDSsanphamLayout);
        jpnDSsanphamLayout.setHorizontalGroup(
            jpnDSsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1753, Short.MAX_VALUE)
        );
        jpnDSsanphamLayout.setVerticalGroup(
            jpnDSsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        jSSanPham.setViewportView(jpnDSsanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jSSanPham;
    private javax.swing.JPanel jpnDSsanpham;
    // End of variables declaration//GEN-END:variables
}
