/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.nhacungcap;

import com.nhom3.qlcf.view.form.users.*;

/**
 *
 * @author baotri1998
 */
public class ChinhSuaNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form Quanlyusers
     */
    public ChinhSuaNhaCungCap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTinhtrang = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblCapNhatTragThai = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblvien2 = new javax.swing.JLabel();
        lblThayDiten = new javax.swing.JLabel();
        lblvien3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblButonReset = new javax.swing.JLabel();
        lblButonCapNhat = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblDiachi = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        lblvien4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblThaydoiSDT = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTinhtrang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTinhtrang.setText("Tình Trạng: Hợp Tác");
        jPanel1.add(lblTinhtrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 331, 43));

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen.setText("Tên Đối Tác: ABC");
        jPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 331, 43));

        lblCapNhatTragThai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCapNhatTragThai.setText("Cập Nhật Trạng Thái :");
        jPanel1.add(lblCapNhatTragThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, 20));

        txtTen.setBorder(null);
        txtTen.setOpaque(false);
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 259, 40));

        lblvien2.setText("___________________________________________");
        jPanel1.add(lblvien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 30));

        lblThayDiten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThayDiten.setText("Thay Đổi Tên:");
        jPanel1.add(lblThayDiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 20));

        lblvien3.setText("___________________________________________");
        jPanel1.add(lblvien3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 260, 30));

        txtSDT.setBorder(null);
        txtSDT.setOpaque(false);
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 259, 40));

        lblButonReset.setBackground(new java.awt.Color(255, 255, 255));
        lblButonReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblButonReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblButonReset.setText("Reset");
        lblButonReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblButonReset.setOpaque(true);
        jPanel1.add(lblButonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        lblButonCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        lblButonCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblButonCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblButonCapNhat.setText("Câp Nhật");
        lblButonCapNhat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblButonCapNhat.setOpaque(true);
        jPanel1.add(lblButonCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 40));

        lblSDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSDT.setText("Số ĐT: 090090090");
        jPanel1.add(lblSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 331, 43));

        lblDiachi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiachi.setText("Địa Chỉ:");
        jPanel1.add(lblDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 43));

        txtDiachi.setBorder(null);
        txtDiachi.setOpaque(false);
        jPanel1.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 259, 40));

        lblvien4.setText("___________________________________________");
        jPanel1.add(lblvien4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không Hợp Tác", "Hợp Tác" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 210, -1));

        lblThaydoiSDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThaydoiSDT.setText("Thay Đổi Số ĐT :");
        jPanel1.add(lblThaydoiSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblButonCapNhat;
    private javax.swing.JLabel lblButonReset;
    private javax.swing.JLabel lblCapNhatTragThai;
    private javax.swing.JLabel lblDiachi;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThayDiten;
    private javax.swing.JLabel lblThaydoiSDT;
    private javax.swing.JLabel lblTinhtrang;
    private javax.swing.JLabel lblvien2;
    private javax.swing.JLabel lblvien3;
    private javax.swing.JLabel lblvien4;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
